const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="colombo,sri lanka."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/colombo";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null.+94769212945";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "+94769212945";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '1'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "true"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "true"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "true"
global.readmessage = process.env.READ_MESSAGE || "true"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "true"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,+94769212945";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,+94769212945";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_06_22_06_16_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTUxLFxuICAgICAgICA2OSxcbiAgICAgICAgNzUsXG4gICAgICAgIDc0LFxuICAgICAgICA4MCxcbiAgICAgICAgMTc4LFxuICAgICAgICAyMTQsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTIwLFxuICAgICAgICAxMyxcbiAgICAgICAgMjAzLFxuICAgICAgICAxOTcsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTgzLFxuICAgICAgICAyNDEsXG4gICAgICAgIDE2MyxcbiAgICAgICAgOTgsXG4gICAgICAgIDExLFxuICAgICAgICAxNTcsXG4gICAgICAgIDIxMixcbiAgICAgICAgMjQ3LFxuICAgICAgICAyMzAsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTMzLFxuICAgICAgICAyMTIsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTEyLFxuICAgICAgICAxNDUsXG4gICAgICAgIDk4LFxuICAgICAgICAxMDVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTMxLFxuICAgICAgICA4LFxuICAgICAgICAyNDUsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTg2LFxuICAgICAgICAxNzMsXG4gICAgICAgIDE4LFxuICAgICAgICAxMCxcbiAgICAgICAgMTQ5LFxuICAgICAgICAyMTgsXG4gICAgICAgIDIsXG4gICAgICAgIDExMixcbiAgICAgICAgMTgwLFxuICAgICAgICAxMzgsXG4gICAgICAgIDk5LFxuICAgICAgICAyMjQsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTIyLFxuICAgICAgICA1NixcbiAgICAgICAgNzEsXG4gICAgICAgIDExOCxcbiAgICAgICAgMzYsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTI3LFxuICAgICAgICAzMyxcbiAgICAgICAgMjUxLFxuICAgICAgICAxNzgsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTEzLFxuICAgICAgICAxMTMsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTE4XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNDQsXG4gICAgICAgIDE3LFxuICAgICAgICAyMjEsXG4gICAgICAgIDIxOCxcbiAgICAgICAgODIsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMjAyLFxuICAgICAgICAzOCxcbiAgICAgICAgMTA0LFxuICAgICAgICAyMDcsXG4gICAgICAgIDMzLFxuICAgICAgICAxNTYsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTI2LFxuICAgICAgICAyMCxcbiAgICAgICAgMTE5LFxuICAgICAgICAxMTMsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTkyLFxuICAgICAgICA3LFxuICAgICAgICAyNDcsXG4gICAgICAgIDEwMixcbiAgICAgICAgNzgsXG4gICAgICAgIDE4NSxcbiAgICAgICAgOTcsXG4gICAgICAgIDE1NixcbiAgICAgICAgMSxcbiAgICAgICAgMTE4LFxuICAgICAgICAxMTksXG4gICAgICAgIDY4LFxuICAgICAgICA2NCxcbiAgICAgICAgODVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjI0LFxuICAgICAgICAxOTIsXG4gICAgICAgIDI1MyxcbiAgICAgICAgNzIsXG4gICAgICAgIDYzLFxuICAgICAgICAxNTksXG4gICAgICAgIDEsXG4gICAgICAgIDYzLFxuICAgICAgICAxMixcbiAgICAgICAgMjE4LFxuICAgICAgICAyMTMsXG4gICAgICAgIDk1LFxuICAgICAgICA3LFxuICAgICAgICAxMzcsXG4gICAgICAgIDI0MixcbiAgICAgICAgNDksXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTQwLFxuICAgICAgICAyMSxcbiAgICAgICAgNzEsXG4gICAgICAgIDY5LFxuICAgICAgICA0MixcbiAgICAgICAgMTA2LFxuICAgICAgICAxNTYsXG4gICAgICAgIDkxLFxuICAgICAgICA5MSxcbiAgICAgICAgMTEwLFxuICAgICAgICAyMzQsXG4gICAgICAgIDI0MixcbiAgICAgICAgMjM1LFxuICAgICAgICAxOTAsXG4gICAgICAgIDQxXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA1NixcbiAgICAgICAgMTExLFxuICAgICAgICAxNTgsXG4gICAgICAgIDIwLFxuICAgICAgICAxMjUsXG4gICAgICAgIDUsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjUxLFxuICAgICAgICAxMTYsXG4gICAgICAgIDIwNSxcbiAgICAgICAgNTAsXG4gICAgICAgIDk5LFxuICAgICAgICAxNDgsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxMixcbiAgICAgICAgODcsXG4gICAgICAgIDI0NCxcbiAgICAgICAgNTksXG4gICAgICAgIDM5LFxuICAgICAgICAxNzMsXG4gICAgICAgIDEwLFxuICAgICAgICAxOSxcbiAgICAgICAgODcsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMzQsXG4gICAgICAgIDIxMixcbiAgICAgICAgNjksXG4gICAgICAgIDExNCxcbiAgICAgICAgNDUsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTA3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTgwLFxuICAgICAgICAxMzMsXG4gICAgICAgIDI0NCxcbiAgICAgICAgODUsXG4gICAgICAgIDIyNyxcbiAgICAgICAgNjgsXG4gICAgICAgIDE2NCxcbiAgICAgICAgNjIsXG4gICAgICAgIDE2OCxcbiAgICAgICAgNDEsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTkxLFxuICAgICAgICAxNDEsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjMsXG4gICAgICAgIDI2LFxuICAgICAgICAxNDcsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTQzLFxuICAgICAgICAyMDksXG4gICAgICAgIDE2LFxuICAgICAgICA1MCxcbiAgICAgICAgMjI4LFxuICAgICAgICAxNzQsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTEwLFxuICAgICAgICAxOSxcbiAgICAgICAgMTU3LFxuICAgICAgICAxMjcsXG4gICAgICAgIDIzNyxcbiAgICAgICAgNDRcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDE5NSxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICA0OCxcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDEsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICAyMzgsXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDEzNSxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDEyNSxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgODdcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAyNCxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICAxNjIsXG4gICAgICAgICAgNDcsXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAyMTMsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDI0NCxcbiAgICAgICAgICAyNDMsXG4gICAgICAgICAgOTQsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgMTY3LFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICA0NyxcbiAgICAgICAgICA4MSxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMjI1LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICA4NVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDc4LFxuICAgICAgICAyMixcbiAgICAgICAgMTU5LFxuICAgICAgICA4NCxcbiAgICAgICAgMTA3LFxuICAgICAgICAxMzgsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjI5LFxuICAgICAgICAxMTIsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTE5LFxuICAgICAgICAxOTgsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMjI4LFxuICAgICAgICAyMjksXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjQsXG4gICAgICAgIDE2LFxuICAgICAgICAxOTAsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTc2LFxuICAgICAgICA2LFxuICAgICAgICAxOTAsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMjA0LFxuICAgICAgICAxOTgsXG4gICAgICAgIDU2LFxuICAgICAgICAxNTAsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMTI3LFxuICAgICAgICA2NixcbiAgICAgICAgMTAxLFxuICAgICAgICA5NCxcbiAgICAgICAgMjQxLFxuICAgICAgICA2NyxcbiAgICAgICAgNDUsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTY2LFxuICAgICAgICAxMzUsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMCxcbiAgICAgICAgMTU1LFxuICAgICAgICA2OCxcbiAgICAgICAgMTIyLFxuICAgICAgICAxNzksXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTQxLFxuICAgICAgICAxNzksXG4gICAgICAgIDUsXG4gICAgICAgIDkzLFxuICAgICAgICAxMDYsXG4gICAgICAgIDc0LFxuICAgICAgICAyNTQsXG4gICAgICAgIDIwOCxcbiAgICAgICAgNDQsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjQyLFxuICAgICAgICAxNDcsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTY0LFxuICAgICAgICAxMixcbiAgICAgICAgNzYsXG4gICAgICAgIDc3LFxuICAgICAgICAxNDBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDIyOCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJ1K24yZnF0V2pvdks5WDZJMjRnN25sUGhqeWxWWHZseHNsaEFHWjRQUi9jPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJSbGtjOXlWOFFiU1NLdngzODRGRU5nXCIsXG4gIFwicGhvbmVJZFwiOiBcIjJmYTZjZGEzLTI4OGYtNDU2Mi05M2U1LWM4ZGJjNzkzZmE0MVwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA5OSxcbiAgICAgIDE0NCxcbiAgICAgIDMyLFxuICAgICAgMTI2LFxuICAgICAgNDYsXG4gICAgICAxOTgsXG4gICAgICA1MCxcbiAgICAgIDE2MSxcbiAgICAgIDEzLFxuICAgICAgMTUxLFxuICAgICAgMjA0LFxuICAgICAgNzMsXG4gICAgICA0OSxcbiAgICAgIDE5NixcbiAgICAgIDEwMCxcbiAgICAgIDIxNixcbiAgICAgIDU4LFxuICAgICAgMTYsXG4gICAgICA2NyxcbiAgICAgIDEzN1xuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IGZhbHNlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTgyLFxuICAgICAgOTAsXG4gICAgICAxMjksXG4gICAgICAyMjEsXG4gICAgICAyMixcbiAgICAgIDY5LFxuICAgICAgMTI1LFxuICAgICAgMTQyLFxuICAgICAgMjMsXG4gICAgICA2NyxcbiAgICAgIDMwLFxuICAgICAgNjcsXG4gICAgICA5NyxcbiAgICAgIDk1LFxuICAgICAgMjE3LFxuICAgICAgMjE2LFxuICAgICAgMTQzLFxuICAgICAgMjIzLFxuICAgICAgMTYzLFxuICAgICAgM1xuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0tmenJ2RUVFSVNKdXJNR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiZXUrYVhETUVaamNWS0pXVnVNVDJiZ2tUVHVtQmI4d05WWXNUdXkycHdDQT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCIzMTBvUndrQkRVZTFNdFptbS9ubUtrYzBTWnRnTnN4eXpCVy9ua2hZRlNJdy9iTVlGS1c2WjdIV0lQZGptdmJzc25MMWpGSEJ6RWI0cEdLVmdwbC9DZz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJyRjI3WFQyUGxueCtnWEtiZCtjMnkrekt3V3RuT20wamNtSW5Wei9weWpNL3R4RWNDZ3ZiU2ZYVThpRE54SmZ6RWNYWTFKTkYyaEE1eU9EUkJOTUZnUT09XCJcbiAgfSxcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjk0NzY5MjEyOTQ1OjEwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxMTY5ODY3Mzg2NjM1NDQ6MTBAbGlkXCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5NDc2OTIxMjk0NToxMEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDEyMixcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDQsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDE0OSxcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDksXG4gICAgICAgICAgMTksXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDEyOSxcbiAgICAgICAgICAxMTEsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDEzOSxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAzMlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzE4NTE4OTIwLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSjVlXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKNWQuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJHRDRuNTZ6dlR5Qm43ZjA2bmRXN0E0VWVPTURWMmwwZDZXMGx1K293dnVnPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEzMTE0ODg0MjAsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcxODQzNjkwNDI4N1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUo1ZS5qc29uIjogIntcImtleURhdGFcIjpcImFIVHJVM0V6Z2VyVTFwazBYNVFWQTJwY1BuNDk3VjJtTXU3VHluRGUwbFU9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTMxMTQ4ODQyMCxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzE4NDM4NTA5ODg2XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSjVmLmpzb24iOiAie1wia2V5RGF0YVwiOlwicHh3dnNFNHdxa2J3KzRYVlEwbTlvTFpOTW1EMEJZRTk5ZGQ3RThtUFRHZz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMzExNDg4NDIxLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKNWcuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCIxTk1pZjVWVnFQM09YcDVqK2tmdkFqNjdCMVVaR2NJRWc0TGFCaXRyZGhNPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEzMTE0ODg0MjEsXCJjdXJyZW50SW5kZXhcIjozLFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsM119LFwidGltZXN0YW1wXCI6XCIxNzE4NTE2MTM2MjcyXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSjVoLmpzb24iOiAie1wia2V5RGF0YVwiOlwicG92MjRxTjNrdkQzTTNLamNLVThFbGhhaXJGWVRwVnI1VTFMcm1XcDhxTT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMzExNDg4NDIxLFwiY3VycmVudEluZGV4XCI6MyxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTg1MTYxNDQ3MDRcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKNWkuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCIrbVZyRUw2ZVBUNFlORlZYMVJxWFlyWGswcHVCWlZrTDJGdDgxS2xJckZRPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEzMTE0ODg0MjEsXCJjdXJyZW50SW5kZXhcIjozLFwiZGV2aWNlSW5kZXhlc1wiOlswXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTg1MTc4MDY3MjhcIn0iCn0="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.7",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "akiyah",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
